# Generated by Django 3.1.4 on 2020-12-10 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attack', models.FloatField()),
                ('attack_growth', models.FloatField()),
                ('shield', models.FloatField()),
                ('shield_growth', models.FloatField()),
                ('health', models.IntegerField()),
                ('health_growth', models.IntegerField()),
                ('health_regen', models.FloatField()),
                ('health_regen_growth', models.FloatField()),
                ('stamina', models.IntegerField()),
                ('stamina_growth', models.IntegerField()),
                ('stamina_regen', models.FloatField()),
                ('stamina_regen_growth', models.FloatField()),
                ('attack_speed', models.FloatField()),
                ('attack_speed_growth', models.FloatField(default=0)),
                ('critical', models.FloatField(default=0)),
                ('critical_growth', models.FloatField(default=0)),
                ('moving_speed', models.FloatField()),
                ('moving_speed_growth', models.FloatField(default=0)),
                ('eyesight', models.IntegerField(default=8)),
                ('eyesight_growth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('attack_speed', models.FloatField()),
                ('attack_speed_growth', models.FloatField()),
                ('additional_damage', models.FloatField()),
                ('additional_damage_growth', models.FloatField()),
                ('amplify_skill_damage', models.FloatField()),
                ('amplify_skill_damage_growth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UsedWeapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
                ('weapon_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.weapon')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
                ('stats', models.TextField()),
                ('detail', models.TextField()),
                ('is_basic', models.CharField(default='basic', max_length=255)),
                ('charac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
        migrations.CreateModel(
            name='Ampli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('damage_taken', models.FloatField(default=0)),
                ('damage_done', models.FloatField(default=0)),
                ('charac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.character')),
            ],
        ),
    ]
