# Generated by Django 3.1.4 on 2020-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='skill_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='weapon',
            name='skill_stats',
            field=models.TextField(default=''),
        ),
    ]
