# Generated by Django 3.1.4 on 2020-12-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0002_animal_respon_time'),
        ('characters', '0003_realampli'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeaponStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('win_rate', models.FloatField()),
                ('pick_rate', models.FloatField()),
                ('charac_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.usedweapon')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
            ],
        ),
        migrations.CreateModel(
            name='WeaponCharacterStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('is_ranker', models.BooleanField()),
                ('win_rate', models.FloatField()),
                ('pick_rate', models.FloatField()),
                ('avg_kill', models.FloatField()),
                ('avg_rank', models.FloatField()),
                ('charac_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.usedweapon')),
            ],
        ),
        migrations.CreateModel(
            name='ModeWeaponCharacterAmpli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoloDamageTaken', models.FloatField()),
                ('SoloDamageGive', models.FloatField()),
                ('DuoDamageTaken', models.FloatField()),
                ('DuoDamageGive', models.FloatField()),
                ('SquadDamageTaken', models.FloatField()),
                ('SquadDamageGive', models.FloatField()),
                ('charac_weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.usedweapon')),
            ],
        ),
        migrations.CreateModel(
            name='ArmorStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=100)),
                ('win_rate', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
            ],
        ),
    ]
