# Generated by Django 3.1.4 on 2021-01-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_armorstat_modeweaponcharacterampli_weaponcharacterstat_weaponstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='armorstat',
            name='duo_win',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='armorstat',
            name='solo_win',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='armorstat',
            name='squad_win',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='armorstat',
            name='mode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='armorstat',
            name='win_rate',
            field=models.FloatField(default=0),
        ),
    ]
