# Generated by Django 3.1.4 on 2020-12-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('first_appear', models.IntegerField(default=60)),
                ('skill', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kinds', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('max_quantity', models.IntegerField(default=1)),
                ('stats', models.TextField()),
                ('material_left', models.IntegerField()),
                ('material_right', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AreaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.area')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
            ],
        ),
        migrations.CreateModel(
            name='AreaAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respon_amount', models.IntegerField(default=1)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.animal')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.area')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_percent', models.FloatField(default=0)),
                ('pocket_number', models.IntegerField(default=1)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.animal')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
            ],
        ),
    ]
