# Generated by Django 3.1.4 on 2021-01-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gamedata', '0002_animal_respon_time'),
        ('characters', '0005_auto_20210101_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playthrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('weapon', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('head', models.IntegerField()),
                ('arm', models.IntegerField()),
                ('leg', models.IntegerField()),
                ('accessory', models.IntegerField()),
                ('characweapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.usedweapon')),
            ],
        ),
        migrations.CreateModel(
            name='Treeitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
                ('play_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playthrough')),
            ],
        ),
        migrations.CreateModel(
            name='Skilltree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('play_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playthrough')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.area')),
                ('play_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playthrough')),
            ],
        ),
        migrations.CreateModel(
            name='Moonstoneitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
                ('play_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playthrough')),
            ],
        ),
        migrations.CreateModel(
            name='Mithrilitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
                ('play_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playthrough')),
            ],
        ),
        migrations.CreateModel(
            name='Meteoritem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
                ('play_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playthrough')),
            ],
        ),
        migrations.CreateModel(
            name='Forcecoreitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
                ('play_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playthrough')),
            ],
        ),
        migrations.CreateModel(
            name='Blooditem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamedata.item')),
                ('play_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.playthrough')),
            ],
        ),
    ]
