# Generated by Django 3.1.4 on 2021-01-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playthrough',
            name='password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
